### ISSUE TITLE
Time Zone issue still persists

### ISSUE THREAD

**Issue by vinceprofeta** [boblauer/mongoose-dateonly#1]
I am saving the dateOnly like so moment(date).format('MM-DD-YYYY') from the client. When I look in robomongo  When I query a range of dates I get back the objects with the proper dates.

Lets say I query for all events between jan 1 - jan 30, the objects come back with the dateOnly objects unchanged. 

If I query for gte: jan 3 and lte jan 3 nothing comes back. I were to change that to the day before, the objects do come back for jan 2 and the dateonly obj has now been changed to jan 2 instead of the 3rd. 

I hope this makes sense. I have been beating my head against the wall trying to figure it out. Everything seems to work fine when I change the time zone of heroku to America but id rather not do that. 

any ideas to what I am doing wrong?

**Comment by boblauer** [comment]
I'm not sure I understand the problem correctly.  Are you able to provide a short code snippet that illustrates the problem?
