### ISSUE TITLE
date only for month 

### ISSUE THREAD

**Issue by fturiot** [boblauer/mongoose-dateonly#5]
Hi ,
for dateOnly i have 20180317 or must be 20180417
what is this problem ?
i thin january is 0

**Comment by boblauer** [comment]
As with the native `Date` object, January is 0:

https://github.com/boblauer/dateonly#api

**Comment by adamreisnz** [comment]
This is a bit ugly in my opinion, and when inspecting the database you could get confused and think the DOB is wrong. Is there any way to use the actual month in the database, so unlike the native Date object? First day of the month is `01` not `00`, so first month of the year should be `01` not `00` for consistency imo.

**Comment by boblauer** [comment]
> First day of the month is 01 not 00, so first month of the year should be 01 not 00 for consistency imo.

I agree with you, but I wanted it to be consistent with the native `Date` object.

**Comment by adamreisnz** [comment]
What about introducing a setting to control this behaviour?

**Comment by boblauer** [comment]
That would complicate the `DateOnly` library, effectively forking many of the methods into 2 separate code paths depending upon the setting.

I agree with you that it's not intuitive, but it's a decision I made to be consistent with `Date`, and adding support for January being 1 is not something I plan on supporting.

Sorry, I know that's not what you want to hear. If you really want this behavior, I would recommend forking `DateOnly` and this library.

**Comment by adamreisnz** [comment]
No worries, I've since rolled our own solution which does the job.
