### ISSUE TITLE
Support for $eq queries

### ISSUE THREAD

**Issue by sandrosimas** [boblauer/mongoose-dateonly#8]
Is there any reason to not support $eq operator?
https://github.com/boblauer/mongoose-dateonly/blob/de1e93c285fbebdfb4c91cbea1ed4a78d9766f8a/lib/schema.js#L27-L38
If there's not reason to not support, I can send a PR.

**Comment by boblauer** [comment]
I believe that is just an oversight, I see no reason why `$eq` shouldn't be supported.

**Comment by sandrosimas** [comment]
@boblauer, I sent the pull request #9.

**Comment by boblauer** [comment]
Thanks for the pull!  Published to npm `@1.0.6`.
